apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-to-end-mlops-platform
  labels:
    app: end-to-end-mlops-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-to-end-mlops-platform
  template:
    metadata:
      labels:
        app: end-to-end-mlops-platform
    spec:
      containers:
        - name: api
          image: end-to-end-mlops-platform:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: end-to-end-mlops-platform
spec:
  selector:
    app: end-to-end-mlops-platform
  ports:
    - port: 80
      targetPort: 8080
